### ISSUE TITLE
incorporating sex into log-linear clock

### ISSUE THREAD

**Issue by JoWhi** [jazoller96/mammalian-methyl-clocks#3]
The log-linear clock depends on age at maturity for the species of interest, but that can be different for males and females, according to getClockDatabase(). The input data for predictAge doesn't include a sex variable; is there an internal function that is predicting sex from the data?

**Comment by jazoller96** [comment]
Yeah, we were aware of this, but for simplicity, when we used a transformation using age of sexual maturity, we simply took the average between males and females, if the values pulled from anAge were different.  Since it's all parametric and our model is assuming a relationship that is much more complex in reality, we find it satisfactory for predicting age accurately.  To make a parameter vary based on sex would be to imply that the aging rate is different between sexes.  The age of sexual maturity parameter simply asks as a scaling parameter for what it means to be roughly "adult" and "done growing rapidly" in that species

**Comment by JoWhi** [comment]
Got it, thanks!
